# Generated by fsm_persistence._generate_code_ids — DO NOT EDIT BY HAND

SET_IDS = ['Player_Default', 'Monster_stupid', 'Monster_Default']
STATES_BY_SET = {'Player_Default': ['Idle', 'Move', 'Attack', 'SpellSelect', 'Damage'], 'Monster_stupid': ['Patrol', 'Damage'], 'Monster_Default': ['Patrol', 'Aggro', 'Chase', 'Attack', 'Flee', 'AlertChase', 'Damage', 'Death']}
TRANSITIONS_BY_SET = {'Player_Default': ['tr_0c3689f0', 'tr_96c80b8d', 'tr_214c2881', 'tr_255caec1', 'tr_01f11810', 'tr_c9e8ee9d'], 'Monster_stupid': ['tr_f5a59d54'], 'Monster_Default': ['tr_7b3eca4d', 'tr_c9ab93b6', 'tr_4e2b5d85', 'tr_abe6f7c7', 'tr_b19a430a', 'tr_50ae2cbf', 'tr_aa2ad20b', 'tr_993675f0', 'tr_1b38f648', 'tr_859db257', 'tr_e89def93', 'tr_2d960c98', 'tr_97b533d3', 'tr_fe48b5d7', 'tr_e2e4cfac']}

__all__ = ['SET_IDS', 'STATES_BY_SET', 'TRANSITIONS_BY_SET']
