using UnityEngine;

namespace Valkur.Data
{
    /// <summary>
    /// One trade the player can practise at a station or from the bag: cooking, blacksmithing,
    /// mining, or the generic crafting bucket everything else falls into. What the player has
    /// LEARNED of it is not stored here — that is the <see cref="skill"/> it points at, on the
    /// same 0-100 % model as woodcutting.
    ///
    /// <para>WHY A ScriptableObject AND NOT AN ENUM. New professions are expected — that was
    /// stated as a requirement, not guessed at — and an enum makes each one a code change in
    /// every place that switches on it, which in this project is exactly how a positional list
    /// grows the four-way tax <c>EntityAssetConfig.attackVariants</c> exists to avoid. A
    /// profession asset means a new trade is a file plus a row in the catalog, reachable from
    /// the Skills editor without recompiling.</para>
    ///
    /// <para>WHY THE KEY IS A STRING AND NOT THIS ASSET'S NAME. The recipe manifest is
    /// generated by Python, which cannot reference a Unity asset — so the join has to be on
    /// something both sides can spell. <c>professionKey</c> is that contract, and
    /// <c>ProfessionCatalog</c> is what turns it back into an object exactly once, at import.
    /// Runtime code holds the reference, never the string.</para>
    /// </summary>
    [CreateAssetMenu(fileName = "NewProfession", menuName = "Valkur/Crafting/Profession")]
    public sealed class ProfessionDefinition : ScriptableObject
    {
        [Header("Identity")]
        [Tooltip("Stable key the recipe manifest joins on: cooking, blacksmith, mining, " +
                 "lumberjack, crafting. Lowercase, no spaces — it is a contract with the " +
                 "Python generator, not a label.")]
        public string professionKey;

        [Tooltip("What the crafting panel and the skills screen call this trade.")]
        public string displayName;

        [TextArea(2, 4)]
        public string description;

        [Header("Presentation")]
        public Sprite icon;

        [Tooltip("Colour used for this trade's tab and its level bar. A trade the player can " +
                 "pick out at a glance is the whole reason the tabs are not all grey.")]
        public Color accentColor = Color.white;

        [Tooltip("Order in the panel's tab strip and the skills screen. Ties fall back to " +
                 "catalog order, which is stable across a re-import.")]
        public int sortOrder;

        [Header("Progression")]
        [Tooltip("The 0-100 % skill this trade trains and is gated by. A profession no longer " +
                 "carries levels of its own: crafting a recipe rolls a gain on this skill, and a " +
                 "recipe's requiredSkill is compared against it. Required — a trade with no skill " +
                 "cannot be learned and its recipes are refused as malformed.")]
        public SkillDefinition skill;

        [Header("Stations")]
        [Tooltip("What a station for this trade is called in the badge and the panel — " +
                 "'cocina', 'fragua', 'banco de trabajo'. A recipe's requiresStation is what " +
                 "decides whether one is needed; this only names it.")]
        public string stationName = "";
    }
}
