using UnityEngine;

namespace Valkur.Data
{
    /// <summary>
    /// One trade the player can practise: cooking, blacksmithing, mining, woodcutting, or the
    /// generic crafting bucket everything else falls into.
    ///
    /// <para>WHY A ScriptableObject AND NOT AN ENUM. New professions are expected — that was
    /// stated as a requirement, not guessed at — and an enum makes each one a code change in
    /// every place that switches on it, which in this project is exactly how a positional list
    /// grows the four-way tax <c>EntityAssetConfig.attackVariants</c> exists to avoid. A
    /// profession asset means a new trade is a file plus a row in the catalog, reachable from
    /// the Skills editor without recompiling.</para>
    ///
    /// <para>WHY THE KEY IS A STRING AND NOT THIS ASSET'S NAME. The recipe manifest is
    /// generated by Python, which cannot reference a Unity asset — so the join has to be on
    /// something both sides can spell. <c>professionKey</c> is that contract, and
    /// <c>ProfessionCatalog</c> is what turns it back into an object exactly once, at import.
    /// Runtime code holds the reference, never the string.</para>
    /// </summary>
    [CreateAssetMenu(fileName = "NewProfession", menuName = "Valkur/Crafting/Profession")]
    public sealed class ProfessionDefinition : ScriptableObject
    {
        [Header("Identity")]
        [Tooltip("Stable key the recipe manifest joins on: cooking, blacksmith, mining, " +
                 "lumberjack, crafting. Lowercase, no spaces — it is a contract with the " +
                 "Python generator, not a label.")]
        public string professionKey;

        [Tooltip("What the crafting panel and the skills screen call this trade.")]
        public string displayName;

        [TextArea(2, 4)]
        public string description;

        [Header("Presentation")]
        public Sprite icon;

        [Tooltip("Colour used for this trade's tab and its level bar. A trade the player can " +
                 "pick out at a glance is the whole reason the tabs are not all grey.")]
        public Color accentColor = Color.white;

        [Tooltip("Order in the panel's tab strip and the skills screen. Ties fall back to " +
                 "catalog order, which is stable across a re-import.")]
        public int sortOrder;

        [Header("Progression")]
        [Tooltip("Highest level this trade can reach.")]
        public int maxLevel = 20;

        [Tooltip("Experience needed to go from level 1 to level 2. Later levels scale by " +
                 "xpGrowth — see XpForNextLevel.")]
        public int baseXpPerLevel = 100;

        [Tooltip("Multiplier applied per level. 1.0 is a flat curve (every level costs the " +
                 "same); the shipped trades use a gentle ramp so late levels are a goal " +
                 "rather than a wall.")]
        public float xpGrowth = 1.25f;

        [Header("Stations")]
        [Tooltip("What a station for this trade is called in the badge and the panel — " +
                 "'cocina', 'fragua', 'banco de trabajo'. A recipe's requiresStation is what " +
                 "decides whether one is needed; this only names it.")]
        public string stationName = "";

        /// <summary>
        /// Experience needed to advance FROM <paramref name="level"/> to the next one.
        ///
        /// <para>Geometric rather than a hand-authored table, for the same reason the dish
        /// prices are derived: a table of twenty numbers per trade is twenty numbers that drift
        /// apart between trades, and nobody can say what the intended shape was. Two authored
        /// values give a curve whose shape is legible and whose retune is one edit.</para>
        ///
        /// <para>Returns 0 at or above <see cref="maxLevel"/>, which is what callers test to
        /// detect a capped trade — never a large number they would have to compare against.</para>
        /// </summary>
        public int XpForNextLevel(int level)
        {
            if (level >= maxLevel) return 0;
            if (level < 1) level = 1;
            float growth = Mathf.Max(1f, xpGrowth);
            return Mathf.Max(1, Mathf.RoundToInt(baseXpPerLevel * Mathf.Pow(growth, level - 1)));
        }
    }
}
