using System;
using UnityEngine;

namespace Valkur.Data
{
    /// <summary>
    /// One ingredient line of a recipe: what it is and how many of it.
    ///
    /// <para>The ingredient is an <see cref="ItemDefinition"/> REFERENCE rather than an id
    /// string, and that is the whole reason a broken recipe is visible. An id is checked only
    /// when something looks it up, so a typo survives every import, every test that does not
    /// happen to craft that item, and shows up as a recipe that silently cannot be made. A
    /// missing asset reference is a null the Inspector draws as "None" and
    /// <see cref="RecipeDefinition.IsWellFormed"/> refuses.</para>
    /// </summary>
    [Serializable]
    public struct RecipeIngredient
    {
        [Tooltip("The raw item consumed. A missing reference makes the whole recipe " +
                 "uncraftable rather than cheaper — see CraftingService.Evaluate.")]
        public ItemDefinition item;

        [Tooltip("How many units of it one craft consumes. Must be at least 1; a zero would " +
                 "be an ingredient the recipe lists and never takes.")]
        public int quantity;

        public RecipeIngredient(ItemDefinition item, int quantity)
        {
            this.item = item;
            this.quantity = quantity;
        }

        public bool IsValid => item != null && quantity > 0;
    }

    /// <summary>
    /// A crafting recipe for any trade: the ingredients that go in, the item that comes out,
    /// which profession makes it, and what it takes to be allowed to.
    ///
    /// <para>ONE RECIPE TYPE FOR EVERY TRADE, not one per trade. Cooking shipped first and had
    /// its own <c>CookRecipeDefinition</c>; adding blacksmithing to that shape would have meant
    /// a second identical class, a second catalog, a second service and a second panel, all
    /// drifting apart on the first change to any of them. What actually differs between
    /// forging a sword and cooking a stew is the PROFESSION, the station and the ingredients —
    /// which are three fields, not three systems.</para>
    ///
    /// <para>WHY THE OUTPUT IS ONE ITEM AND NOT A WEIGHTED TABLE. The value of the panel to the
    /// player is being able to PLAN — read it, see what is missing, go and get it — and a
    /// random output makes that planning meaningless. Every shipped recipe maps one set of
    /// ingredients onto one result.</para>
    ///
    /// <para>Generated by <c>Valkur &gt; Crafting &gt; Import Crafting Content</c> from
    /// <c>tools/atlas/generated/crafting_manifest.json</c>, and editable in game from the
    /// Skills editor. The importer rewrites the DERIVED numbers on every run and fills prose
    /// only when empty — see <c>CraftingContentImporter</c> on why this half does not follow
    /// the usual "authored value wins" rule.</para>
    /// </summary>
    [CreateAssetMenu(fileName = "NewRecipe", menuName = "Valkur/Crafting/Recipe")]
    public sealed class RecipeDefinition : ScriptableObject
    {
        [Header("Identity")]
        [Tooltip("Stable id. Matches the output item's id for every shipped recipe, which is " +
                 "the key the generated manifest joins on.")]
        public string recipeId;

        [Tooltip("What the crafting panel calls this row.")]
        public string displayName;

        [Header("Trade")]
        [Tooltip("Which profession makes this. A recipe with no profession is unreachable " +
                 "from the panel — every tab is a profession — so this is required.")]
        public ProfessionDefinition profession;

        [Tooltip("Free-form grouping WITHIN a profession: the cuisine for a dish, the material " +
                 "tier for a forged blade. A VIEW, not a category — it only decides how the " +
                 "panel subdivides a long list.")]
        public string group;

        [Header("Output")]
        public ItemDefinition output;

        [Tooltip("How many units one craft yields.")]
        public int outputQuantity = 1;

        [Header("Input")]
        public RecipeIngredient[] ingredients = Array.Empty<RecipeIngredient>();

        [Header("Requirements")]
        [Tooltip("Whether a station for this profession must be in range.")]
        public bool requiresStation;

        [Tooltip("Skill, in whole percent (0-100), the player needs in this profession's skill. " +
                 "0 means available from the start. It is also the recipe's DIFFICULTY for the " +
                 "gain roll: cooking something far below your skill teaches only the floor.")]
        [Range(0, 100)] public int requiredSkill;

        [Tooltip("Gain rolls one successful craft makes on the profession's skill. Scaled off the " +
                 "recipe's own cost by the generator, so a hallaca teaches more than a skyr.")]
        [Min(0)] public int skillGainRolls = 1;

        [Tooltip("Seconds one craft takes.")]
        public float craftSeconds = 1f;

        /// <summary>Total units of raw material one craft consumes.</summary>
        public int TotalIngredientUnits
        {
            get
            {
                int total = 0;
                if (ingredients == null) return 0;
                for (int i = 0; i < ingredients.Length; i++)
                    if (ingredients[i].IsValid) total += ingredients[i].quantity;
                return total;
            }
        }

        /// <summary>
        /// Whether this recipe could ever be crafted. False for one missing its output, its
        /// profession (or its skill), or carrying a broken ingredient line — a DATA defect rather than a
        /// player-facing state, which is why the panel hides such a row instead of greying it
        /// out and sending the player to look for something that does not exist.
        /// </summary>
        public bool IsWellFormed
        {
            get
            {
                if (output == null || outputQuantity <= 0) return false;
                if (profession == null || profession.skill == null) return false;
                if (ingredients == null || ingredients.Length == 0) return false;
                for (int i = 0; i < ingredients.Length; i++)
                    if (!ingredients[i].IsValid) return false;
                return true;
            }
        }
    }
}
