using System.Collections.Generic;
using System.IO;
using System.Linq;
using NUnit.Framework;
using UnityEngine;
using Valkur.Editor.FSM;
using Valkur.Gameplay.FSM;
using Valkur.Gameplay.World; // MiniJsonRuntime

namespace Valkur.Tests.EditMode.Editors.FSM
{
    /// <summary>
    /// Pins the fix for "a seed regeneration silently discards F12 edits": before this,
    /// <see cref="FSMSeedGenerator.MergeSetsIdempotent"/> dropped any existing
    /// <c>auto_generated: true</c> set outright the instant its id matched a freshly
    /// generated one — full replace, not a merge — which is indistinguishable from
    /// deleting every transition/blackboard/layout edit a designer made in F12. The
    /// shipped <c>Monster_Default</c> carries three authored transitions
    /// (t_chase_flee, t_attack_flee, t_any_alert) that drive <see cref="FleeState"/> and
    /// <see cref="AlertChaseState"/>; a regen used to delete all three.
    ///
    /// The fix makes the merge additive: only the STATE VOCABULARY is refreshed (new
    /// state ids appended), everything else on the set — transitions, blackboard,
    /// label, initial, every already-present state's own fields — is left untouched.
    /// </summary>
    [TestFixture]
    public class FSMSeedGeneratorMergePreservesAuthoredEditsTests
    {
        [Test]
        public void MergeSetsIdempotent_PreservesAuthoredTransitions_OnAnAutoGeneratedSet()
        {
            var existing = BuildExistingMonsterDefault(
                stateIds: new[] { nameof(IdleState), nameof(ChaseState) },
                transitions: new[]
                {
                    ("t_chase_flee", "ChaseState", "FleeState", "hp_pct < 0.25", 100, 180),
                    ("t_attack_flee", "AttackState", "FleeState", "hp_pct < 0.25", 100, 180),
                    ("t_any_alert", "*", "AlertChaseState",
                        "time_since_hit < 0.5 && distance_to_player > aggro_range", 200, 300),
                });
            var fresh = FSMSeedGenerator.BuildDefaultSetsRoot(
                FSMSeedGenerator.DefaultStates, FSMSeedGenerator.INITIAL_STATE);

            var merged = FSMSeedGenerator.MergeSetsIdempotent(existing, fresh);
            var set = SoleSet(merged);

            var transitions = TransitionsOf(set);
            Assert.AreEqual(3, transitions.Count,
                "All three authored transitions must survive a regen of the vocabulary.");
            AssertTransition(transitions, "t_chase_flee", "ChaseState", "FleeState", "hp_pct < 0.25", 100, 180);
            AssertTransition(transitions, "t_attack_flee", "AttackState", "FleeState", "hp_pct < 0.25", 100, 180);
            AssertTransition(transitions, "t_any_alert", "*", "AlertChaseState",
                "time_since_hit < 0.5 && distance_to_player > aggro_range", 200, 300);
        }

        [Test]
        public void MergeSetsIdempotent_RefreshesStateVocabulary_WithoutTouchingExistingStatesOrTransitions()
        {
            var existing = BuildExistingMonsterDefault(
                stateIds: FSMSeedGenerator.DefaultStates,
                transitions: new[] { ("t_chase_flee", "ChaseState", "FleeState", "hp_pct < 0.25", 100, 180) });

            // Hand-edit one existing state's label/position, the way a designer dragging
            // a node or renaming it in the Properties panel would.
            var existingStates = StatesOf(SoleSet(existing));
            var idleState = existingStates.First(s => (string)s["id"] == nameof(IdleState));
            idleState["label"] = "Sneaking";
            idleState["x"] = 999L;

            // Simulate the codebase gaining a brand-new state class since the last regen.
            var extendedIds = FSMSeedGenerator.DefaultStates.Append("VoidState").ToArray();
            var fresh = FSMSeedGenerator.BuildDefaultSetsRoot(extendedIds, FSMSeedGenerator.INITIAL_STATE);

            var merged = FSMSeedGenerator.MergeSetsIdempotent(existing, fresh);
            var set = SoleSet(merged);
            var states = StatesOf(set);

            Assert.AreEqual(FSMSeedGenerator.DefaultStates.Length + 1, states.Count,
                "The new state class must be appended to the vocabulary.");
            CollectionAssert.Contains(states.Select(s => (string)s["id"]).ToList(), "VoidState",
                "A newly introduced state class must show up in the next regen.");

            var idleAfter = states.First(s => (string)s["id"] == nameof(IdleState));
            Assert.AreEqual("Sneaking", idleAfter["label"],
                "An already-present state's hand-edited fields must not be reset by a regen.");
            Assert.AreEqual(999L, idleAfter["x"],
                "An already-present state's position must not be reset by a regen.");

            var transitions = TransitionsOf(set);
            Assert.AreEqual(1, transitions.Count,
                "Transitions must be untouched by a vocabulary-only refresh.");
        }

        [Test]
        public void MergeSetsIdempotent_PreservesBlackboardAndLabel_OnAnAutoGeneratedSet()
        {
            var existing = BuildExistingMonsterDefault(
                stateIds: FSMSeedGenerator.DefaultStates, transitions: System.Array.Empty<(string, string, string, string, int, int)>());
            var set = SoleSet(existing);
            set["label"] = "Custom Label From F12";
            ((Dictionary<string, object>)set["blackboard"])["aggro_bonus"] = 2L;

            var fresh = FSMSeedGenerator.BuildDefaultSetsRoot(
                FSMSeedGenerator.DefaultStates, FSMSeedGenerator.INITIAL_STATE);

            var merged = FSMSeedGenerator.MergeSetsIdempotent(existing, fresh);
            var mergedSet = SoleSet(merged);

            Assert.AreEqual("Custom Label From F12", mergedSet["label"],
                "A hand-edited label must survive a regen.");
            var blackboard = (Dictionary<string, object>)mergedSet["blackboard"];
            Assert.AreEqual(2L, blackboard["aggro_bonus"],
                "Blackboard entries must survive a regen.");
        }

        // ── Real shipped data ────────────────────────────────────────────────────

        [Test]
        public void MergeSetsIdempotent_ShippedMonsterDefault_AuthoredTransitionsSurviveARegen()
        {
            string path = Path.Combine(Application.streamingAssetsPath, "FSM", "sets.json");
            Assert.IsTrue(File.Exists(path), $"Shipped sets.json must exist at '{path}'.");

            var shipped = MiniJsonRuntime.Deserialize(File.ReadAllText(path)) as Dictionary<string, object>;
            Assert.IsNotNull(shipped, "Shipped sets.json must parse as a JSON object.");

            var fresh = FSMSeedGenerator.BuildDefaultSetsRoot(
                FSMSeedGenerator.DefaultStates, FSMSeedGenerator.INITIAL_STATE);

            var merged = FSMSeedGenerator.MergeSetsIdempotent(shipped, fresh);
            var sets = (List<object>)merged["sets"];
            var defaultSet = sets.Cast<Dictionary<string, object>>()
                .First(s => (string)s["id"] == FSMSeedGenerator.DEFAULT_SET_ID);

            var transitions = TransitionsOf(defaultSet);
            Assert.AreEqual(3, transitions.Count,
                "Monster_Default ships three authored transitions that drive FleeState and " +
                "AlertChaseState — a regen must not drop any of them.");
            AssertTransition(transitions, "t_chase_flee", "ChaseState", "FleeState", "hp_pct < 0.25", 100, 180);
            AssertTransition(transitions, "t_attack_flee", "AttackState", "FleeState", "hp_pct < 0.25", 100, 180);
            AssertTransition(transitions, "t_any_alert", "*", "AlertChaseState",
                "time_since_hit < 0.5 && distance_to_player > aggro_range", 200, 300);
        }

        // ── Helpers ──────────────────────────────────────────────────────────────

        private static Dictionary<string, object> BuildExistingMonsterDefault(
            string[] stateIds,
            (string id, string from, string to, string guard, int priority, int cooldownFrames)[] transitions)
        {
            var root = FSMSeedGenerator.BuildDefaultSetsRoot(stateIds, FSMSeedGenerator.INITIAL_STATE);
            var set = SoleSet(root);
            var trList = new List<object>();
            foreach (var t in transitions)
            {
                trList.Add(new Dictionary<string, object>
                {
                    ["id"] = t.id, ["from"] = t.from, ["to"] = t.to,
                    ["guard"] = t.guard, ["when"] = "", ["event"] = "",
                    ["priority"] = (long)t.priority, ["cooldown_frames"] = (long)t.cooldownFrames,
                    ["actions"] = new List<object>(),
                });
            }
            set["transitions"] = trList;
            return root;
        }

        private static Dictionary<string, object> SoleSet(Dictionary<string, object> root)
            => (Dictionary<string, object>)((List<object>)root["sets"])[0];

        private static List<Dictionary<string, object>> StatesOf(Dictionary<string, object> set)
            => ((List<object>)set["states"]).Cast<Dictionary<string, object>>().ToList();

        private static List<Dictionary<string, object>> TransitionsOf(Dictionary<string, object> set)
            => ((List<object>)set["transitions"]).Cast<Dictionary<string, object>>().ToList();

        private static void AssertTransition(
            List<Dictionary<string, object>> transitions, string id, string from, string to,
            string guard, int priority, int cooldownFrames)
        {
            var tr = transitions.FirstOrDefault(t => (string)t["id"] == id);
            Assert.IsNotNull(tr, $"Transition '{id}' must survive the regen.");
            Assert.AreEqual(from, tr["from"], $"'{id}'.from must round-trip.");
            Assert.AreEqual(to, tr["to"], $"'{id}'.to must round-trip.");
            Assert.AreEqual(guard, tr["guard"], $"'{id}'.guard must round-trip.");
            Assert.AreEqual((long)priority, System.Convert.ToInt64(tr["priority"]), $"'{id}'.priority must round-trip.");
            Assert.AreEqual((long)cooldownFrames, System.Convert.ToInt64(tr["cooldown_frames"]),
                $"'{id}'.cooldown_frames must round-trip.");
        }
    }
}
