using System.Collections.Generic;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;
using Valkur.Data;
using Valkur.Gameplay;

namespace Valkur.Tests.EditMode.Game.Data
{
    /// <summary>
    /// Pins the shipped data for <c>knight_red</c>, the first entity in the catalog with a
    /// genuinely animated attack and the only user of the attack-variant path.
    ///
    /// <see cref="PlayerSpriteIntegrityTests"/> exists because a texture-import setting
    /// silently nulled 23 of 40 walk frames on every player and the walk cycle degraded to
    /// two frames per direction — visible, but only if you were looking. The knight is
    /// exposed to the same class of failure and then some: its 120 frames were generated by
    /// a tool outside the repo (<c>tools/atlas/wave2/build_knight_frames.py</c>), its four
    /// linear sheets and five variants are 64 references each, and the east-facing half of
    /// every one of them is a DIFFERENT set of sprites from the west — the pre-mirrored
    /// copies, because DirectionalAnimator never flips a sprite.
    ///
    /// So the failure to guard against is not only a null: it is a bucket filled with the
    /// wrong side, which renders a knight moonwalking east while facing west and trips no
    /// exception anywhere.
    /// </summary>
    public class KnightRedSpriteIntegrityTests
    {
        private const string DefinitionPath =
            "Assets/_Project/Data/Catalogs/Monsters/knight_red.asset";
        private const string CatalogPath =
            "Assets/_Project/Data/Catalogs/Monsters/MonsterCatalog.asset";

        /// <summary>Eight directions of eight frames, in the animator's bucket order.</summary>
        private const int FramesPerDirection = 8;
        private const int Directions = 8;
        private const int LinearFrameCount = FramesPerDirection * Directions;

        /// <summary>
        /// Which side of the art each direction bucket must draw from, in the order
        /// DirectionalAnimator slices a linear list: S, SE, E, NE, N, NW, W, SW.
        /// The three east-facing directions take the mirrored copies.
        /// </summary>
        private static readonly string[] SideByDirection =
            { "w", "e", "e", "e", "w", "w", "w", "w" };

        private static readonly string[] ExpectedVariants =
            { "slash", "shieldbash", "punch", "kick", "jumpkick" };

        private static MonsterDefinition Definition()
        {
            var def = AssetDatabase.LoadAssetAtPath<MonsterDefinition>(DefinitionPath);
            Assert.IsNotNull(def, $"knight_red is missing at {DefinitionPath}");
            Assert.IsNotNull(def.assetConfig, "knight_red assetConfig must not be null");
            return def;
        }

        /// <summary>Every linear sheet on the definition, by the slot it fills.</summary>
        private static IEnumerable<(string slot, List<Sprite> frames)> LinearSheets(EntityAssetConfig c)
        {
            yield return ("walkSheets", c.walkSheets);
            yield return ("chaseSheets", c.chaseSheets);
            yield return ("attackSheets", c.attackSheets);
            yield return ("castSheets", c.castSheets);
            foreach (AttackVariant v in c.attackVariants)
                yield return ($"variant:{v.key}", v.sheets);
        }

        // ---- Registration -----------------------------------------------------

        [Test]
        public void KnightRed_IsRegisteredInTheMonsterCatalog()
        {
            var catalog = AssetDatabase.LoadAssetAtPath<MonsterCatalog>(CatalogPath);
            Assert.IsNotNull(catalog, $"MonsterCatalog is missing at {CatalogPath}");

            // Nothing can spawn a definition the catalog cannot resolve by key.
            Assert.IsNotNull(catalog.GetByKey("knight_red"),
                "knight_red is not registered — MonsterCatalog.GetByKey returns null.");
        }

        // ---- Idle: the authored turnaround ------------------------------------

        [Test]
        public void Idle_WiresAllEightDirections()
        {
            DirectionalSprites idle = Definition().assetConfig.idle;

            // Idle is the one state the art actually turns for. A missing direction here
            // does not fail: the binder falls through to a neighbour and the knight simply
            // faces the wrong way while standing still.
            Assert.IsNotNull(idle.south, "idle.south");
            Assert.IsNotNull(idle.southEast, "idle.southEast");
            Assert.IsNotNull(idle.east, "idle.east");
            Assert.IsNotNull(idle.northEast, "idle.northEast");
            Assert.IsNotNull(idle.north, "idle.north");
            Assert.IsNotNull(idle.northWest, "idle.northWest");
            Assert.IsNotNull(idle.west, "idle.west");
            Assert.IsNotNull(idle.southWest, "idle.southWest");
        }

        // ---- Linear sheets ----------------------------------------------------

        [Test]
        public void EverySheet_HasTheFullEightByEightFrameCount()
        {
            var wrong = new List<string>();
            foreach (var (slot, frames) in LinearSheets(Definition().assetConfig))
            {
                if (frames == null || frames.Count != LinearFrameCount)
                    wrong.Add($"{slot}: {frames?.Count.ToString() ?? "null"} (want {LinearFrameCount})");
            }

            // A short list is not an error anywhere in the engine: BuildEightDirectionalSet
            // just divides by 8 and hands out fewer frames per direction.
            Assert.IsEmpty(wrong,
                "Sheets with the wrong frame count — re-run the knight frame build: " +
                string.Join(", ", wrong));
        }

        [Test]
        public void NoSheet_ContainsANullFrame()
        {
            var holes = new List<string>();
            foreach (var (slot, frames) in LinearSheets(Definition().assetConfig))
            {
                if (frames == null) continue;
                for (int i = 0; i < frames.Count; i++)
                    if (frames[i] == null) holes.Add($"{slot}[{i}]");
            }

            // This is the exact shape of the bug PlayerSpriteIntegrityTests was written for:
            // the binder filters nulls, so the cycle silently loses frames rather than throwing.
            Assert.IsEmpty(holes, "Null sprite references: " + string.Join(", ", holes));
        }

        [Test]
        public void EveryBucket_DrawsFromTheSideItsDirectionFaces()
        {
            var wrong = new List<string>();
            foreach (var (slot, frames) in LinearSheets(Definition().assetConfig))
            {
                if (frames == null || frames.Count != LinearFrameCount) continue;

                for (int dir = 0; dir < Directions; dir++)
                {
                    string want = $"_{SideByDirection[dir]}";
                    for (int f = 0; f < FramesPerDirection; f++)
                    {
                        Sprite sprite = frames[dir * FramesPerDirection + f];
                        if (sprite == null) continue;

                        // Names are knight_red_<family>_<w|e><frame>.
                        string name = sprite.name;
                        int split = name.LastIndexOf('_');
                        string side = split >= 0 && split + 1 < name.Length
                            ? $"_{name[split + 1]}" : "?";

                        if (side != want)
                            wrong.Add($"{slot} dir{dir} frame{f} is '{name}' (want a {want} sprite)");
                    }
                }
            }

            Assert.IsEmpty(wrong,
                "Direction buckets drawing from the wrong side — the knight would face away " +
                "from where it moves: " + string.Join("; ", wrong.GetRange(0, Mathf.Min(8, wrong.Count))));
        }

        [Test]
        public void EveryBucket_RunsItsFramesInOrder()
        {
            var wrong = new List<string>();
            foreach (var (slot, frames) in LinearSheets(Definition().assetConfig))
            {
                if (frames == null || frames.Count != LinearFrameCount) continue;

                for (int dir = 0; dir < Directions; dir++)
                {
                    for (int f = 0; f < FramesPerDirection; f++)
                    {
                        Sprite sprite = frames[dir * FramesPerDirection + f];
                        if (sprite == null) continue;

                        // The trailing digit is the frame ordinal the generator wrote.
                        char last = sprite.name[sprite.name.Length - 1];
                        if (last - '0' != f)
                            wrong.Add($"{slot} dir{dir} slot{f} holds '{sprite.name}'");
                    }
                }
            }

            // A shuffled bucket animates, so nothing looks broken — the swing just reads as
            // stuttering or playing backwards.
            Assert.IsEmpty(wrong, "Frames out of order: " +
                string.Join("; ", wrong.GetRange(0, Mathf.Min(8, wrong.Count))));
        }

        // ---- Variants ---------------------------------------------------------

        [Test]
        public void Variants_AreTheFiveExpectedFamiliesWithSlashFirst()
        {
            List<AttackVariant> variants = Definition().assetConfig.attackVariants;
            Assert.IsNotNull(variants, "attackVariants must not be null");

            var keys = new List<string>();
            foreach (AttackVariant v in variants) keys.Add(v.key);

            CollectionAssert.AreEqual(ExpectedVariants, keys,
                "Index 0 is the swing a picker falls back to, so slash must stay first.");
        }

        [Test]
        public void Variants_DoNotShareSpritesWithEachOther()
        {
            List<AttackVariant> variants = Definition().assetConfig.attackVariants;
            var owner = new Dictionary<Sprite, string>();
            var shared = new List<string>();

            foreach (AttackVariant v in variants)
            {
                if (v.sheets == null) continue;
                foreach (Sprite s in v.sheets)
                {
                    if (s == null) continue;
                    if (owner.TryGetValue(s, out string first))
                    {
                        if (first != v.key) shared.Add($"{s.name} in both {first} and {v.key}");
                    }
                    else owner[s] = v.key;
                }
            }

            // Two variants sharing frames means one of them was built from the wrong family,
            // which reads in game as "the kick sometimes plays the punch".
            Assert.IsEmpty(shared, "Variants sharing sprites: " +
                string.Join("; ", shared.GetRange(0, Mathf.Min(5, shared.Count))));
        }

        // ---- End to end -------------------------------------------------------

        [Test]
        public void Binder_ProducesEightFramesPerDirectionForEveryVariant()
        {
            MonsterDefinition def = Definition();
            var go = new GameObject("KnightBindTarget");
            try
            {
                go.AddComponent<SpriteRenderer>();
                Assert.IsTrue(EntityAnimationBinder.ApplyMonsterVisuals(go, def),
                    "ApplyMonsterVisuals refused the knight");

                var anim = go.GetComponent<DirectionalAnimator>();
                Assert.AreEqual(ExpectedVariants.Length, anim.AttackVariantCount,
                    "A variant with no frames is dropped by the binder, so a count below " +
                    "the authored one means one of them failed to resolve.");

                // The number the whole 64-entry convention exists to produce.
                var walk = DirectionalAnimator.CreateSetFromLinearFrames(def.assetConfig.walkSheets);
                Assert.AreEqual(FramesPerDirection, walk.south.Length, "walk south");
                Assert.AreEqual(FramesPerDirection, walk.east.Length, "walk east");
                Assert.AreEqual(FramesPerDirection, walk.north.Length, "walk north");
                Assert.AreEqual(FramesPerDirection, walk.west.Length, "walk west");
            }
            finally
            {
                Object.DestroyImmediate(go);
            }
        }

        [Test]
        public void ScaleIsLeftToTheSprites_SoApplyEntityScaleStaysOut()
        {
            AnimationScaleConfig scale = Definition().assetConfig.scaleConfig;

            // The frames are already authored at game size (PPU 64, ~113 px tall). A non-zero
            // scaleIdle would send ApplyEntityScale through its Python-parity formula and
            // resize the knight by a factor of the PPU ratio.
            Assert.AreEqual(0f, scale.scaleIdle, 0.0001f,
                "scaleIdle must stay 0 so ApplyEntityScale does not re-scale the knight.");
        }
    }
}
