// Regression suite for the picker/loader category-manifest fix.
//
// Before this fix, Resources/Tiles/ category folders were two independently
// hardcoded arrays: TileCatalog.BuildFromResources() (9 entries — the picker)
// and OverlayLoader.CATEGORY_FOLDERS (13 entries — the world painter). They
// had already diverged from each other AND from disk: 4 folders existed on
// disk with zero way to select them from the picker, and 11 loose root
// sprites (floor, wall, dungeon_floor…) were painted in shipped maps yet
// completely unreachable from the tile picker.
//
// The fix replaced both hardcoded arrays with a single baked artifact —
// Resources/Tiles/_categories.json, generated by
// Scripts/Editor/Asset/TileCategoryManifestBuilder.cs from a real
// AssetDatabase scan — that both TileCatalog and OverlayLoader now read.
//
// These tests do NOT call TileCategoryManifestBuilder or trust the baked
// JSON's content at face value. Every test here re-derives the "ground
// truth" straight from AssetDatabase, independently of production code, so
// a regression that reintroduces a second hardcoded list — even one that
// coincidentally matches the manifest on the day it's written — fails the
// moment disk and catalog/loader disagree.

using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;
using Valkur.Gameplay.TileEditor;
using Valkur.Gameplay.World;

namespace Valkur.Tests.EditMode.Editors.TileEditor.Catalog
{
    [TestFixture]
    public class TileCategoryDiskParityTests
    {
        private const string TILES_ROOT = "Assets/_Project/Resources/Tiles";
        private const string MANIFEST_ASSET_PATH = TILES_ROOT + "/_categories.json";

        private TileCatalog _catalog;

        [OneTimeSetUp]
        public void OneTimeSetUp()
        {
            _catalog = TileCatalog.BuildFromResources();
        }

        [OneTimeTearDown]
        public void OneTimeTearDown()
        {
            if (_catalog == null) return;
            foreach (var entry in _catalog.Entries)
                if (entry.tile != null) Object.DestroyImmediate(entry.tile);
            Object.DestroyImmediate(_catalog);
            _catalog = null;
        }

        // ── Ground-truth helpers (independent of TileCategoryManifestBuilder) ──

        /// <summary>
        /// Immediate subfolders of Resources/Tiles/ that contain at least one sprite
        /// anywhere beneath them, read fresh from AssetDatabase every call.
        /// </summary>
        private static HashSet<string> DiscoverDiskFolderCategories()
        {
            var result = new HashSet<string>();
            foreach (var sub in AssetDatabase.GetSubFolders(TILES_ROOT))
            {
                int spriteCount = AssetDatabase.FindAssets("t:Sprite", new[] { sub }).Length;
                if (spriteCount > 0) result.Add(Path.GetFileName(sub));
            }
            return result;
        }

        /// <summary>
        /// Sprite file names (no extension) that sit directly under Resources/Tiles/
        /// with no owning subfolder — e.g. floor, wall, dungeon_floor.
        /// </summary>
        private static HashSet<string> DiscoverDiskRootLooseSpriteNames()
        {
            var result = new HashSet<string>();
            foreach (var guid in AssetDatabase.FindAssets("t:Sprite", new[] { TILES_ROOT }))
            {
                string assetPath = AssetDatabase.GUIDToAssetPath(guid);
                string parentDir = Path.GetDirectoryName(assetPath)?.Replace('\\', '/');
                if (parentDir != TILES_ROOT) continue;
                result.Add(Path.GetFileNameWithoutExtension(assetPath));
            }
            return result;
        }

        /// <summary>
        /// Reads the manifest's declared synthetic-root-category NAME only (not its
        /// folder list) — needed so tests don't hardcode "basics" and silently stop
        /// meaning anything if the name is ever renamed.
        /// </summary>
        private static string ReadSyntheticRootCategoryName()
        {
            var asset = AssetDatabase.LoadAssetAtPath<TextAsset>(MANIFEST_ASSET_PATH);
            // TextAsset is a UnityEngine.Object — use != null, not Assert.IsNotNull,
            // which would pass on a Unity fake-null.
            Assert.IsTrue(asset != null, $"{MANIFEST_ASSET_PATH} is missing — the single source of " +
                "truth for tile categories was deleted.");
            var manifest = JsonUtility.FromJson<TileCategoryManifest>(asset.text);
            Assert.IsNotNull(manifest, $"{MANIFEST_ASSET_PATH} failed to parse as TileCategoryManifest.");
            Assert.IsFalse(string.IsNullOrEmpty(manifest.syntheticRootCategory),
                "Manifest must declare a non-empty syntheticRootCategory.");
            return manifest.syntheticRootCategory;
        }

        /// <summary>
        /// Reads OverlayLoader's private CategoryFolders property via reflection —
        /// there is no public accessor because it exists purely as a resolve-order
        /// speed hint, but that's exactly the state a "second hardcoded list"
        /// regression would live in, so the test needs to see the real value.
        /// </summary>
        private static string[] GetOverlayLoaderCategoryFolders()
        {
            var prop = typeof(OverlayLoader).GetProperty("CategoryFolders",
                BindingFlags.NonPublic | BindingFlags.Static);
            Assert.IsNotNull(prop, "OverlayLoader.CategoryFolders property not found by reflection " +
                "— has it been renamed or removed?");
            return (string[])prop.GetValue(null);
        }

        // ── Requirement 1: disk → catalog parity (the picker) ──────────────

        [Test]
        public void FolderCategories_LiveDiskEnumeration_AllAppearInCatalog()
        {
            var diskFolders = DiscoverDiskFolderCategories();
            Assert.Greater(diskFolders.Count, 0,
                "Sanity: Resources/Tiles/ must contain at least one sprite-bearing subfolder.");

            var catalogCategories = new HashSet<string>(_catalog.GetCategories());

            var missing = diskFolders.Where(f => !catalogCategories.Contains(f)).ToList();
            Assert.IsEmpty(missing,
                "Folder(s) under Resources/Tiles/ contain sprites on disk but are NOT selectable " +
                "picker categories: " + string.Join(", ", missing) + ". This is the two-hardcoded-" +
                "lists regression — categories must come from the shared _categories.json manifest, " +
                "not a hand-maintained array.");
        }

        [Test]
        public void FolderCategories_CatalogHasNoStaleCategoriesAbsentFromDisk()
        {
            var diskFolders = DiscoverDiskFolderCategories();
            string synthetic = ReadSyntheticRootCategoryName();

            var stale = _catalog.GetCategories()
                .Where(c => c != synthetic && !diskFolders.Contains(c))
                .ToList();

            Assert.IsEmpty(stale,
                "Catalog exposes categor(y/ies) with no matching sprite-bearing Resources/Tiles/ " +
                "subfolder on disk: " + string.Join(", ", stale) + ". Stale manifest entry (folder " +
                "renamed/deleted but the baked _categories.json wasn't regenerated).");
        }

        // ── Requirement 1, applied to the world painter too ────────────────

        [Test]
        public void OverlayLoader_CategoryFolders_MatchLiveDiskEnumeration()
        {
            var diskFolders = DiscoverDiskFolderCategories();
            var loaderFolders = new HashSet<string>(GetOverlayLoaderCategoryFolders());

            CollectionAssert.AreEquivalent(diskFolders, loaderFolders,
                "OverlayLoader.CategoryFolders has drifted from the real Resources/Tiles/ folder " +
                "tree. This is the two-hardcoded-lists bug on the world-paint side: the loader must " +
                "read the same manifest as the picker, not its own hand-maintained array.");
        }

        // ── Requirement 2: single source of truth ──────────────────────────

        [Test]
        public void TileCatalog_And_OverlayLoader_ShareIdenticalCategoryListAndOrder()
        {
            string synthetic = ReadSyntheticRootCategoryName();
            var catalogFolderCategories = _catalog.GetCategories()
                .Where(c => c != synthetic)
                .ToArray();

            var loaderFolders = GetOverlayLoaderCategoryFolders();

            CollectionAssert.AreEqual(loaderFolders, catalogFolderCategories,
                "TileCatalog (picker) and OverlayLoader (world paint) must be built from the exact " +
                "same folder list, in the exact same order, sourced from the one baked manifest. A " +
                "mismatch here means a second, independent category list has reappeared — even if " +
                "its content happens to look right today, it will silently drift from disk again.");
        }

        // ── Requirement 4: synthetic root category ─────────────────────────

        [Test]
        public void TileCatalog_SyntheticRootCategory_ExposesAllLooseRootSprites_IncludingFloor()
        {
            var diskRootFiles = DiscoverDiskRootLooseSpriteNames();
            Assert.IsTrue(diskRootFiles.Contains("floor"),
                "Fixture sanity: Resources/Tiles/floor.png must exist as a loose root sprite for " +
                "this regression test to mean anything.");

            var byTileName = _catalog.Entries.ToDictionary(e => e.tileName, e => e.category);

            var observedCategories = new HashSet<string>();
            var unselectable = new List<string>();
            foreach (var rootFile in diskRootFiles)
            {
                if (!byTileName.TryGetValue(rootFile, out var category))
                {
                    unselectable.Add(rootFile);
                    continue;
                }
                observedCategories.Add(category);
            }

            Assert.IsEmpty(unselectable,
                "Loose root sprite(s) under Resources/Tiles/ are not selectable from the tile " +
                "picker: " + string.Join(", ", unselectable));

            Assert.AreEqual(1, observedCategories.Count,
                "All loose root sprites must be grouped under a single synthetic category, not " +
                "scattered across several — found: " + string.Join(", ", observedCategories));

            string synthetic = observedCategories.Single();
            var diskFolderCategories = DiscoverDiskFolderCategories();
            Assert.IsFalse(diskFolderCategories.Contains(synthetic),
                $"Synthetic root category '{synthetic}' collides with a real Resources/Tiles/ " +
                "subfolder name — it must stay a synthetic bucket that owns no folder on disk.");
        }
    }
}
