using System;
using System.Collections.Generic;
using UnityEngine;
using Valkur.Data;

namespace Valkur.Gameplay.Crafting
{
    /// <summary>What the player has reached in one trade.</summary>
    public readonly struct ProfessionProgress
    {
        public readonly int Level;
        public readonly int Xp;

        /// <summary>Experience still needed for the next level. 0 at the cap.</summary>
        public readonly int XpForNext;

        public ProfessionProgress(int level, int xp, int xpForNext)
        {
            Level = level;
            Xp = xp;
            XpForNext = xpForNext;
        }

        public bool IsMaxed => XpForNext <= 0;

        /// <summary>
        /// Progress towards the next level, 0..1. Returns 1 at the cap rather than 0, because
        /// a full bar is what "finished" looks like and an empty one reads as a bug.
        /// </summary>
        public float Fraction01 => IsMaxed ? 1f : Mathf.Clamp01((float)Xp / XpForNext);
    }

    /// <summary>
    /// The player's standing in every trade: cooking, blacksmithing, mining, woodcutting and
    /// whatever is added next.
    ///
    /// <para>KEYED BY STRING, NOT BY ASSET REFERENCE. A save file has to name a profession
    /// somehow, and a serialized asset reference is exactly what breaks when the asset is
    /// regenerated by an importer — which these are. The key is the same contract the recipe
    /// manifest joins on, so a save, a recipe and a profession asset all agree by spelling
    /// rather than by GUID.</para>
    ///
    /// <para>UNKNOWN TRADES READ AS LEVEL 1, NEVER 0. A profession the player has never
    /// practised must not be a locked one — every trade starts available and the level gate is
    /// what a recipe opts into. Returning 0 would refuse every recipe with the default
    /// <c>requiredLevel = 1</c> and make the whole crafting system inert on a fresh character,
    /// silently. That is the shape this project has shipped a dozen times over and named
    /// authored-and-inert.</para>
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class PlayerProfessions : MonoBehaviour
    {
        /// <summary>Every trade starts here. See the class note on why this is 1 and not 0.</summary>
        public const int STARTING_LEVEL = 1;

        [Serializable]
        private struct Entry
        {
            public string key;
            public int level;
            public int xp;
        }

        [SerializeField]
        [Tooltip("Serialized so a character's trades survive a domain reload mid-Play and are " +
                 "visible in the Inspector while debugging. Written through AddXp, never by " +
                 "hand.")]
        private List<Entry> _entries = new List<Entry>();

        /// <summary>
        /// Raised when a trade gains a level. Carries the KEY rather than the asset, so a
        /// listener that only wants to show a toast does not have to resolve the catalog.
        /// </summary>
        public event Action<string, int> OnProfessionLevelUp;

        /// <summary>Raised on every xp gain, levelled or not.</summary>
        public event Action<string, int> OnProfessionXpGained;

        private int IndexOf(string key)
        {
            for (int i = 0; i < _entries.Count; i++)
                if (string.Equals(_entries[i].key, key, StringComparison.OrdinalIgnoreCase))
                    return i;
            return -1;
        }

        /// <summary>The player's level in <paramref name="key"/>. Never below 1.</summary>
        public int GetLevel(string key)
        {
            if (string.IsNullOrEmpty(key)) return STARTING_LEVEL;
            int i = IndexOf(key);
            return i < 0 ? STARTING_LEVEL : Mathf.Max(STARTING_LEVEL, _entries[i].level);
        }

        /// <summary>Level and experience in one trade, resolved against its own curve.</summary>
        public ProfessionProgress GetProgress(ProfessionDefinition profession)
        {
            if (profession == null) return new ProfessionProgress(STARTING_LEVEL, 0, 0);

            int i = IndexOf(profession.professionKey);
            int level = i < 0 ? STARTING_LEVEL : Mathf.Max(STARTING_LEVEL, _entries[i].level);
            int xp = i < 0 ? 0 : _entries[i].xp;
            return new ProfessionProgress(level, xp, profession.XpForNextLevel(level));
        }

        /// <summary>
        /// Grant experience and level up as far as it carries.
        ///
        /// <para>A WHILE LOOP, not a single comparison: one craft may legitimately cross more
        /// than one level on a trade whose early curve is cheap, and levelling only once would
        /// silently bank the remainder against a threshold the player has already passed. It is
        /// bounded by the profession's own <c>maxLevel</c> through <c>XpForNextLevel</c>
        /// returning 0 at the cap, which is also what stops the loop.</para>
        /// </summary>
        public void AddXp(ProfessionDefinition profession, int amount)
        {
            if (profession == null || amount <= 0) return;
            if (string.IsNullOrEmpty(profession.professionKey)) return;

            int i = IndexOf(profession.professionKey);
            if (i < 0)
            {
                _entries.Add(new Entry
                {
                    key = profession.professionKey,
                    level = STARTING_LEVEL,
                    xp = 0,
                });
                i = _entries.Count - 1;
            }

            var entry = _entries[i];
            entry.xp += amount;

            int gained = 0;
            int needed = profession.XpForNextLevel(entry.level);
            while (needed > 0 && entry.xp >= needed)
            {
                entry.xp -= needed;
                entry.level++;
                gained++;
                needed = profession.XpForNextLevel(entry.level);
            }

            // A capped trade banks nothing: leaving experience on a level that can never be
            // spent shows a bar creeping up forever behind a number that cannot move.
            if (needed <= 0) entry.xp = 0;

            _entries[i] = entry;

            OnProfessionXpGained?.Invoke(profession.professionKey, amount);
            for (int n = 0; n < gained; n++)
                OnProfessionLevelUp?.Invoke(profession.professionKey, entry.level - gained + n + 1);
        }

        // ── Persistence ──────────────────────────────────────────────────────────

        /// <summary>Write this component's state into the save document.</summary>
        public void WriteTo(ProgressionSaveData data)
        {
            if (data == null) return;
            data.professionKeys = new List<string>(_entries.Count);
            data.professionLevels = new List<int>(_entries.Count);
            data.professionXp = new List<int>(_entries.Count);

            for (int i = 0; i < _entries.Count; i++)
            {
                data.professionKeys.Add(_entries[i].key);
                data.professionLevels.Add(_entries[i].level);
                data.professionXp.Add(_entries[i].xp);
            }
        }

        /// <summary>
        /// Restore from the save document.
        ///
        /// <para>Reads only as far as the SHORTEST of the three lists. They are written
        /// together and should always match, but a hand-edited or truncated save must not throw
        /// an IndexOutOfRange inside the load path — losing one trade's progress is recoverable,
        /// failing to load the character is not.</para>
        /// </summary>
        public void ReadFrom(ProgressionSaveData data)
        {
            _entries.Clear();
            if (data?.professionKeys == null) return;

            int count = data.professionKeys.Count;
            if (data.professionLevels != null) count = Mathf.Min(count, data.professionLevels.Count);
            else return;
            if (data.professionXp != null) count = Mathf.Min(count, data.professionXp.Count);
            else return;

            for (int i = 0; i < count; i++)
            {
                if (string.IsNullOrEmpty(data.professionKeys[i])) continue;
                _entries.Add(new Entry
                {
                    key = data.professionKeys[i],
                    level = Mathf.Max(STARTING_LEVEL, data.professionLevels[i]),
                    xp = Mathf.Max(0, data.professionXp[i]),
                });
            }
        }
    }
}
