using System.Collections.Generic;
using System.IO;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;
using Valkur.Gameplay.World;

namespace Valkur.Tests.EditMode.Game.World.Buildings
{
    /// <summary>
    /// Data-integrity tests for the shipped building interior, generated by
    /// <c>tools/maps/generate_interior_overlay.py</c>.
    ///
    /// An interior is the one piece of this feature that is CONTENT rather than code, and a
    /// broken one fails in the worst possible place: the world is already cleared by the time
    /// the loader finds out, so the player is standing in a void. <see cref="WorldTransitionService"/>
    /// checks loadability before tearing anything down, and this fixture checks that the
    /// shipped room passes that check and is actually a room — walls all the way round, and a
    /// spawn point inside them.
    ///
    /// The spawn assertion is the spawner incident's lesson applied early: assert the shipped
    /// coordinate is IN BOUNDS, not merely that the format round-trips.
    /// </summary>
    [TestFixture]
    public class InteriorOverlayContentTests
    {
        private const string OVERLAY = "Interiors/house_interior_small.overlay.json";

        /// <summary>Spawn point printed by the generator and used by the shipped doorway.</summary>
        private static readonly Vector2 SUGGESTED_SPAWN = new Vector2(7.5f, 5.5f);

        [TearDown]
        public void TearDown() => LogAssert.ignoreFailingMessages = false;

        private static string Path_() => WorldTransitionService.ResolveOverlayPath(OVERLAY);

        private static Dictionary<string, object> Root()
        {
            string p = Path_();
            Assume.That(File.Exists(p), $"Interior overlay missing: {p}. Regenerate it with " +
                                        "python tools/maps/generate_interior_overlay.py");
            var root = OverlayLoader.ParseOverlay(p);
            Assert.IsNotNull(root, "Interior overlay did not parse as a JSON object.");
            return root;
        }

        private static List<List<string>> Layer(string name)
        {
            var root = Root();
            Assert.IsTrue(root.TryGetValue("layers", out var layersRaw), "No 'layers' key.");
            var layers = layersRaw as Dictionary<string, object>;
            Assert.IsNotNull(layers, "'layers' is not an object.");
            Assert.IsTrue(layers.TryGetValue(name, out var rowsRaw), $"No '{name}' layer.");

            var rows = rowsRaw as List<object>;
            Assert.IsNotNull(rows, $"'{name}' is not a matrix.");

            var outRows = new List<List<string>>();
            foreach (var r in rows)
            {
                var cells = r as List<object>;
                Assert.IsNotNull(cells, $"A row of '{name}' is not a list.");
                var line = new List<string>();
                foreach (var c in cells) line.Add(c as string ?? "");
                outRows.Add(line);
            }
            return outRows;
        }

        // ── Loadability ─────────────────────────────────────────────────────────

        [Test]
        [Category("DataIntegrity")]
        public void ShippedInterior_ExistsAndIsLoadable()
        {
            Assert.IsTrue(File.Exists(Path_()), $"Missing: {Path_()}");
            Assert.IsTrue(WorldTransitionService.IsOverlayLoadable(OVERLAY),
                "The transition service refuses this file, so every doorway pointing at it " +
                "would be rejected at author time and at entry time.");
        }

        [Test]
        [Category("DataIntegrity")]
        public void Interiors_LiveInTheirOwnFolder_NotBesideTheZoneOverlays()
        {
            // Everything DIRECTLY under StreamingAssets/Maps is a 50x50 tile of the base
            // world: WorldLoader composes them by offset, and
            // RealShippedOverlayBoundsAndNamesTests asserts that exact size for every file it
            // finds there. An interior is a room of whatever size the room is, so it cannot
            // live in that folder without either breaking that invariant or forcing it to
            // grow an exception list - and an invariant with exceptions stops catching the
            // malformed zone it exists to catch.
            //
            // This test is the reason the first interior was moved rather than the reason the
            // rule was loosened.
            string interiorsDir = System.IO.Path.Combine(
                Application.streamingAssetsPath, "Maps", "Interiors");

            Assert.IsTrue(Directory.Exists(interiorsDir),
                $"Interiors folder missing: {interiorsDir}");

            StringAssert.Contains("Interiors", OVERLAY,
                "The shipped interior must be addressed through the Interiors subfolder.");

            Assert.Greater(Directory.GetFiles(interiorsDir, "*.overlay.json").Length, 0,
                "No interior overlays shipped. Regenerate with " +
                "python tools/maps/generate_interior_overlay.py");
        }

        [Test]
        public void AMissingOverlay_IsNotLoadable()
        {
            Assert.IsFalse(WorldTransitionService.IsOverlayLoadable("no_such_room.overlay.json"));
            Assert.IsFalse(WorldTransitionService.IsOverlayLoadable(""));
            Assert.IsFalse(WorldTransitionService.IsOverlayLoadable(null));
        }

        // ── Shape ───────────────────────────────────────────────────────────────

        [Test]
        [Category("DataIntegrity")]
        public void ShippedInterior_IsARectangularGroundedRoom()
        {
            var ground = Layer("Ground");

            Assert.Greater(ground.Count, 4, "A room smaller than 5 rows has no interior once walled.");
            int width = ground[0].Count;
            Assert.Greater(width, 4, "A room narrower than 5 columns has no interior once walled.");

            foreach (var row in ground)
            {
                Assert.AreEqual(width, row.Count, "Ragged rows: the room is not rectangular.");
                foreach (var cell in row)
                    Assert.IsNotEmpty(cell, "A hole in the Ground layer reads as a pit in the floor.");
            }
        }

        [Test]
        [Category("DataIntegrity")]
        public void ShippedInterior_IsSealedByWallsOnEverySide()
        {
            var collision = Layer("Collision");
            int rows = collision.Count;
            int cols = collision[0].Count;

            for (int x = 0; x < cols; x++)
            {
                Assert.IsNotEmpty(collision[0][x],        $"Gap in the top wall at column {x}.");
                Assert.IsNotEmpty(collision[rows - 1][x], $"Gap in the bottom wall at column {x}.");
            }
            for (int y = 0; y < rows; y++)
            {
                Assert.IsNotEmpty(collision[y][0],        $"Gap in the left wall at row {y}.");
                Assert.IsNotEmpty(collision[y][cols - 1], $"Gap in the right wall at row {y}.");
            }
        }

        [Test]
        [Category("DataIntegrity")]
        public void ShippedInterior_HasAWalkableInside()
        {
            var collision = Layer("Collision");
            int rows = collision.Count;
            int cols = collision[0].Count;

            int walkable = 0;
            for (int y = 1; y < rows - 1; y++)
                for (int x = 1; x < cols - 1; x++)
                    if (string.IsNullOrEmpty(collision[y][x])) walkable++;

            Assert.AreEqual((rows - 2) * (cols - 2), walkable,
                "Every cell inside the wall ring must be walkable — a solid interior is a room " +
                "the player is teleported into and immediately stuck in.");
        }

        // ── The spawn point ─────────────────────────────────────────────────────

        [Test]
        [Category("DataIntegrity")]
        public void SuggestedSpawn_LandsInsideTheWalls()
        {
            var collision = Layer("Collision");
            int rows = collision.Count;
            int cols = collision[0].Count;

            // Row 0 of the matrix is the TOP and the loader flips Y, so a matrix `rows` tall
            // occupies Unity cells y in [0, rows).
            int cellX = Mathf.FloorToInt(SUGGESTED_SPAWN.x);
            int cellY = Mathf.FloorToInt(SUGGESTED_SPAWN.y);
            int row   = rows - 1 - cellY;

            Assert.GreaterOrEqual(cellX, 1, "Spawn is on or outside the left wall.");
            Assert.LessOrEqual(cellX, cols - 2, "Spawn is on or outside the right wall.");
            Assert.GreaterOrEqual(row, 1, "Spawn is on or outside the top wall.");
            Assert.LessOrEqual(row, rows - 2, "Spawn is on or outside the bottom wall.");

            Assert.IsEmpty(collision[row][cellX],
                $"The spawn cell ({cellX}, {cellY}) is painted solid. The player would be " +
                "teleported inside a wall — the exact class of failure the spawner " +
                "coordinate-space drift produced, caught here by asserting the shipped value " +
                "is in bounds rather than that the format round-trips.");
        }
    }
}
